ProyectoGestionHotelera/Controllers/PersonaController.cs
// Espacios de nombres necesarios
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;


namespace ProyectoGestionHotelera.Controllers
{
    // Definición de la clase PersonaController que hereda de Controller
    public class PersonaController : Controller
    {
        // Propiedad para almacenar las reservaciones (modelo)
        public List<string> Reservaciones { get; set; }

        // Acción para mostrar la vista de búsqueda de persona
        public IActionResult BuscarPersona()
        {
            return View();
        }

        // Acción de búsqueda de reservaciones por persona (POST)
        [HttpPost]
        public IActionResult BuscarPorPersona(string cedulaIdentidad)
        {
            // Validación de la longitud de la cédula
            if (!ValidarCedula(cedulaIdentidad))
            {
                ModelState.AddModelError(string.Empty, "La cédula de identidad no cumple con los requisitos.");
                // Carga todas las reservaciones
                CargarReservaciones();
                return View("BuscarPersona");
            }

            // Carga las reservaciones según la cédula proporcionada
            CargarReservaciones(cedulaIdentidad);
            return View("BuscarPersona", Reservaciones);
        }

        // Acción para mostrar todas las reservaciones
        public IActionResult FiltrarTodos()
        {
            // Carga todas las reservaciones
            CargarReservaciones();
            return View("BuscarPersona");
        }

        // Método para cargar todas las reservaciones
        public IActionResult CargarReservaciones()
        {
            // Inicializa la lista de reservaciones
            Reservaciones = new List<string>();

            // Cadena de conexión a la base de datos
            string connectionString = "Server=ADSP-13207\\MSSQLSERVER01;Database=GestionHotelera;Trusted_Connection=True;TrustServerCertificate=true;";

            // Consulta para seleccionar todas las reservaciones
            string queryString = "SELECT Nombre, PrimerApellido, SegundoApellido, CedulaIdentidad, Nacionalidad, Telefono, CorreoElectronico, NombreHotel, Torre, Piso, NumeroHabitacion FROM Reservaciones";

            // Uso de la conexión a la base de datos
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                SqlCommand command = new SqlCommand(queryString, connection);
                connection.Open();
                SqlDataReader reader = command.ExecuteReader();

                // Lectura de resultados y almacenamiento en la lista de reservaciones
                while (reader.Read())
                {
                    string reservacion = ObtenerDatosReservacion(reader);
                    Reservaciones.Add(reservacion);
                }

                reader.Close();
            }

            // Devuelve la vista con el modelo de reservaciones
            return View("BuscarPersona", Reservaciones);
        }

        // Método para cargar reservaciones según la cédula proporcionada
        private void CargarReservaciones(string cedulaIdentidad)
        {
            // Inicializa la lista de reservaciones
            Reservaciones = new List<string>();

            // Cadena de conexión a la base de datos
            string connectionString = "Server=ADSP-13207\\MSSQLSERVER01;Database=GestionHotelera;Trusted_Connection=True;TrustServerCertificate=true;";

            // Consulta para seleccionar reservaciones según la cédula proporcionada
            string queryString = "SELECT Nombre, PrimerApellido, SegundoApellido, CedulaIdentidad, Nacionalidad, Telefono, CorreoElectronico, NombreHotel, Torre, Piso, NumeroHabitacion FROM Reservaciones WHERE CedulaIdentidad = @CedulaIdentidad";

            // Uso de la conexión a la base de datos
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                SqlCommand command = new SqlCommand(queryString, connection);
                command.Parameters.AddWithValue("@CedulaIdentidad", cedulaIdentidad);
                connection.Open();
                SqlDataReader reader = command.ExecuteReader();

                // Lectura de resultados y almacenamiento en la lista de reservaciones
                while (reader.Read())
                {
                    string reservacion = ObtenerDatosReservacion(reader);
                    Reservaciones.Add(reservacion);
                }

                reader.Close();
            }
        }

        // Método para obtener datos de una reservación en formato de cadena
        private string ObtenerDatosReservacion(SqlDataReader reader)
        {
            string nombre = reader["Nombre"].ToString();
            string primerApellido = reader["PrimerApellido"].ToString();
            string segundoApellido = reader["SegundoApellido"].ToString();
            string cedulaId = reader["CedulaIdentidad"].ToString();
            string nacionalidad = reader["Nacionalidad"].ToString();
            string telefono = reader["Telefono"].ToString();
            string correoElectronico = reader["CorreoElectronico"].ToString();
            string nombreHotel = reader["NombreHotel"].ToString();
            string torre = reader["Torre"].ToString();
            string piso = reader["Piso"].ToString();
            string numeroHabitacion = reader["NumeroHabitacion"].ToString();

            return $"{nombre}, {primerApellido}, {segundoApellido}, {cedulaId}, {nacionalidad}, {telefono}, {correoElectronico}, {nombreHotel}, {torre}, {piso}, {numeroHabitacion}";
        }

        // Método para validar la longitud de la cédula
        private bool ValidarCedula(string cedula)
        {
            return cedula.Length == 11;
        }
    }
}

ProyectoGestionHotelera/Controllers/ReservacionController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;


namespace ProyectoGestionHotelera.Controllers
{
    // Definición de la clase ReservacionController que hereda de Controller
    public class ReservacionController : Controller
    {
        // Acción para mostrar la vista principal de reservaciones
        public IActionResult Reservacion()
        {
            return View();
        }

        // Acción de reserva automática (POST)
        [HttpPost]
        public IActionResult ReservaAutomatica(string nombre, string primerApellido, string segundoApellido, string cedulaIdentidad, string nacionalidad, string telefono, string correoElectronico, string nombreHotel)
        {
            // Cadena de conexión a la base de datos
            string connectionString = "Server=ADSP-13207\\MSSQLSERVER01;Database=GestionHotelera;Trusted_Connection=True;TrustServerCertificate=true;";

            if (!string.IsNullOrEmpty(nombreHotel))
            {
                // Uso de la conexión a la base de datos
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    // Consulta para obtener la primera habitación disponible en el hotel especificado
                    string primeraHabitacionDisponibleQuery = "SELECT TOP 1 Torre, Piso, NumeroHabitacion FROM Habitaciones " +
                                                               "WHERE Nombre = @NombreHotel AND Disponibilidad = 1 " +
                                                               "ORDER BY Torre, Piso, NumeroHabitacion";

                    // Uso de un comando para ejecutar la consulta
                    using (SqlCommand primeraHabitacionCommand = new SqlCommand(primeraHabitacionDisponibleQuery, connection))
                    {
                        primeraHabitacionCommand.Parameters.AddWithValue("@NombreHotel", nombreHotel);

                        // Uso de un lector de datos para obtener resultados de la consulta
                        using (SqlDataReader primeraHabitacionReader = primeraHabitacionCommand.ExecuteReader())
                        {
                            if (primeraHabitacionReader.Read())
                            {
                                // Obtener detalles de la habitación disponible
                                string torre = primeraHabitacionReader["Torre"].ToString();
                                string piso = primeraHabitacionReader["Piso"].ToString();
                                string numeroHabitacion = primeraHabitacionReader["NumeroHabitacion"].ToString();

                                // Consulta para insertar la reserva en la tabla Reservaciones
                                string insertQuery = "INSERT INTO Reservaciones (Nombre, PrimerApellido, SegundoApellido, CedulaIdentidad, Nacionalidad, Telefono, CorreoElectronico, NombreHotel, Torre, Piso, NumeroHabitacion) " +
                                                    "VALUES (@Nombre, @PrimerApellido, @SegundoApellido, @CedulaIdentidad, @Nacionalidad, @Telefono, @CorreoElectronico, @NombreHotel, @Torre, @Piso, @NumeroHabitacion)";

                                // Uso de otro comando para ejecutar la inserción
                                using (SqlCommand command = new SqlCommand(insertQuery, connection))
                                {
                                    // Parámetros para la inserción
                                    command.Parameters.AddWithValue("@Nombre", nombre);
                                    command.Parameters.AddWithValue("@PrimerApellido", primerApellido);
                                    command.Parameters.AddWithValue("@SegundoApellido", segundoApellido);
                                    command.Parameters.AddWithValue("@CedulaIdentidad", cedulaIdentidad);
                                    command.Parameters.AddWithValue("@Nacionalidad", nacionalidad);
                                    command.Parameters.AddWithValue("@Telefono", telefono);
                                    command.Parameters.AddWithValue("@CorreoElectronico", correoElectronico);
                                    command.Parameters.AddWithValue("@NombreHotel", nombreHotel);
                                    command.Parameters.AddWithValue("@Torre", torre);
                                    command.Parameters.AddWithValue("@Piso", piso);
                                    command.Parameters.AddWithValue("@NumeroHabitacion", numeroHabitacion);

                                    // Ejecutar la inserción
                                    command.ExecuteNonQuery();
                                }

                                // Consulta para actualizar la disponibilidad de la habitación a no disponible (0)
                                string updateDisponibilidadQuery = "UPDATE Habitaciones " +
                                                                   "SET Disponibilidad = 0 " +
                                                                   "WHERE Nombre = @NombreHotel AND Torre = @Torre AND Piso = @Piso AND NumeroHabitacion = @NumeroHabitacion";

                                // Otro comando para ejecutar la actualización de disponibilidad
                                using (SqlCommand updateCommand = new SqlCommand(updateDisponibilidadQuery, connection))
                                {
                                    // Parámetros para la actualización
                                    updateCommand.Parameters.AddWithValue("@NombreHotel", nombreHotel);
                                    updateCommand.Parameters.AddWithValue("@Torre", torre);
                                    updateCommand.Parameters.AddWithValue("@Piso", piso);
                                    updateCommand.Parameters.AddWithValue("@NumeroHabitacion", numeroHabitacion);

                                    // Ejecutar la actualización
                                    updateCommand.ExecuteNonQuery();
                                }

                                // Mensaje de éxito
                                TempData["Mensaje"] = "Reserva guardada con éxito";
                                TempData["Tipo"] = "Ok";
                            }
                            else
                            {
                                // No hay habitaciones disponibles en el hotel especificado
                                TempData["Mensaje"] = "Lo sentimos, no hay habitaciones disponibles en este momento en el hotel " + nombreHotel;
                                TempData["Tipo"] = "error";

                                // Redireccionar a la acción de reserva automática
                                return RedirectToAction("ReservacionAutomatica");
                            }
                        }
                    }
                }
            }

            // Redireccionar a la acción de reserva automática
            return RedirectToAction("ReservacionAutomatica");
        }

        // Acción para mostrar la vista de reserva automática
        public IActionResult ReservacionAutomatica()
        {
            return View();
        }

        // Acción para mostrar la vista de reserva manual
        public IActionResult ReservacionManual()
        {
            return View();
        }

        // Acción de reserva manual (POST)
        [HttpPost]
        public IActionResult ReservaManual(string nombre, string primerApellido, string segundoApellido, string cedulaIdentidad, string nacionalidad, string telefono, string correoElectronico, string nombreHotel, string torre, string piso, string numeroHabitacion)
        {
            // Cadena de conexión a la base de datos
            string connectionString = "Server=ADSP-13207\\MSSQLSERVER01;Database=GestionHotelera;Trusted_Connection=True;TrustServerCertificate=true;";

            if (!string.IsNullOrEmpty(nombreHotel))
            {
                // Uso de la conexión a la base de datos
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    // Consulta para verificar la disponibilidad de la habitación
                    string disponibilidadQuery = "SELECT Disponibilidad FROM Habitaciones " +
                                                 "WHERE Nombre = @NombreHotel AND Torre = @Torre AND Piso = @Piso AND NumeroHabitacion = @NumeroHabitacion";

                    // Uso de un comando para ejecutar la consulta
                    using (SqlCommand disponibilidadCommand = new SqlCommand(disponibilidadQuery, connection))
                    {
                        // Parámetros para la consulta
                        disponibilidadCommand.Parameters.AddWithValue("@NombreHotel", nombreHotel);
                        disponibilidadCommand.Parameters.AddWithValue("@Torre", int.Parse(torre));
                        disponibilidadCommand.Parameters.AddWithValue("@Piso", int.Parse(piso));
                        disponibilidadCommand.Parameters.AddWithValue("@NumeroHabitacion", int.Parse(numeroHabitacion));

                        // Obtener el resultado de la consulta
                        object disponibilidadResult = disponibilidadCommand.ExecuteScalar();

                        if (disponibilidadResult != null && disponibilidadResult != DBNull.Value)
                        {
                            int disponibilidad = Convert.ToInt32(disponibilidadResult);

                            if (disponibilidad == 1)
                            {
                                // La habitación está disponible, procede con la reservación

                                // Consulta para insertar la reserva en la tabla Reservaciones

ProyectoGestionHotelera/Views/Reservacion/Reservacion.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Reservaciones";
}

<div class="container mt-4">
    <h1 class="text-center">Tipo de Reservación</h1>

    <div class="row mt-4">
        <div class="col-md-6 text-center">
            <a asp-controller="Reservacion" asp-action="ReservacionManual" class="text-decoration-none">
                <div>
                    <img src="~/Imagenes/Manual.png" alt="Reservación Manual" style="width:200px; height:200px;">
                    <p>Reservación Manual</p>
                </div>
            </a>
        </div>
        <div class="col-md-6 text-center">
            <a asp-controller="Reservacion" asp-action="ReservacionAutomatica" class="text-decoration-none">
                <div>
                    <img src="~/Imagenes/Automatica.png" alt="Reservación Automática" style="width:200px; height:200px;">
                    <p>Reservación Automática</p>
                </div>
            </a>
        </div>

        <div class="col-md-6 text-center">
            <a asp-controller="ReservaEliminar" asp-action="CargarReservaciones" class="text-decoration-none">
                <div>
                    <img src="~/Imagenes/Borrar.png" alt="Eliminar Reservarción" style="width:200px; height:200px;">
                    <p>Eliminar Reservarción</p>
                </div>
            </a>
        </div>
        <div class="col-md-6 text-center">
            <a asp-controller="Persona" asp-action="CargarReservaciones" class="text-decoration-none">
                <div>
                    <img src="~/Imagenes/Persona.png" alt="Buscar Persona" style="width:200px; height:200px;">
                    <p>Buscar Persona</p>
                </div>
            </a>
        </div>


        <div class="col-md-6 text-center">
            <a asp-controller="Hoteles" asp-action="CargarHabitaciones" class="text-decoration-none">
                <div>
                    <img src="~/Imagenes/Habitaciones.jpg" alt="Buscar Habitacion" style="width:200px; height:200px;">
                    <p>Buscar Habitacion Disponible</p>
                </div>
            </a>
        </div>


    </div>

    @* <a href="#" class="btn btn-primary position-fixed top-0 end-0 m-3">Administrar</a> *@
</div>

ProyectoGestionHotelera/Views/Reservacion/ReservacionAutomatica.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Reservación Automatica";
}

<style>
    .error-message {
        color: red;
        font-size: 0.9em;
        margin-top: 0.25rem;
    }

    .custom-spinner {
        color: #28a745; /* Color verde */
    }

    .message-container {
        margin-right: 10px;
    }

    #mensaje {
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        display: none;
        text-align: center;
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
</style>


<div class="container">
    <h1 class="mt-4 mb-4 text-center">Registrar Reservación Automatica</h1>

    <form method="post" action="/Reservacion/ReservaAutomatica" class="m-3 p-3 border border-primary needs-validation" novalidate>
        <div class="form-group">
            <label for="nombreHotel">Seleccione un hotel:</label>
            <select id="nombreHotel" name="nombreHotel" class="form-control" required>
                <option value="Hotel Continental de New York">Hotel Continental de New York</option>
                <option value="Hotel Continental de Roma">Hotel Continental de Roma</option>
                <option value="Hotel Continental de Marruecos">Hotel Continental de Marruecos</option>
                <option value="Hotel Continental de Osaka Tokyo">Hotel Continental de Osaka Tokyo</option>
            </select>
        </div>

        <div class="form-group">
            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="Nombre" class="form-control" required>
            <div class="invalid-feedback">
                Por favor, complete este campo.
            </div>
        </div>

        <div class="form-group">
            <label for="primerApellido">Primer Apellido:</label>
            <input type="text" id="primerApellido" name="PrimerApellido" class="form-control" required>
            <div class="invalid-feedback">
                Por favor, complete este campo.
            </div>
        </div>

        <div class="form-group">
            <label for="segundoApellido">Segundo Apellido:</label>
            <input type="text" id="segundoApellido" name="SegundoApellido" class="form-control" required>
            <div class="invalid-feedback">
                Por favor, complete este campo.
            </div>
        </div>

        <div class="form-group">
            <label for="nacionalidad">Nacionalidad:</label>
            <select id="nacionalidad" name="Nacionalidad" class="form-control" required>
                <!-- Opciones de nacionalidad se cargarán dinámicamente mediante JavaScript -->
            </select>
            <div class="invalid-feedback">
                Por favor, seleccione una nacionalidad.
            </div>
        </div>

        <div class="form-group">
            <label for="cedulaIdentidad">Número de Cédula o DIMEX:</label>
            <input type="text" id="cedulaIdentidad" name="CedulaIdentidad" onchange="validarCedula(this)" class="form-control" required>
            <div class="invalid-feedback">
                Por favor, proporcione un número de cédula o DIMEX válido.
            </div>
        </div>

        <div class="form-group">
            <label for="telefono">Número de Teléfono:</label>
            <div class="input-group">
                <select id="codigoPais" name="CodigoPais" class="form-control input-group-prepend" required>
                    <option value="+1">+1 (Estados Unidos)</option>
                    <option value="+1-684">+1-684 (Samoa Americana)</option>
                    <option value="+1-671">+1-671 (Guam)</option>
                    <option value="+1-876">+1-876 (Jamaica)</option>
                    <option value="+1-868">+1-868 (Trinidad y Tobago)</option>
                    <option value="+1-649">+1-649 (Islas Turcas y Caicos)</option>
                    <option value="+1-340">+1-340 (Islas Vírgenes de EE. UU.)</option>
                    <option value="+44">+44 (Reino Unido)</option>
                    <option value="+49">+49 (Alemania)</option>
                    <option value="+33">+33 (Francia)</option>
                    <option value="+34">+34 (España)</option>
                    <option value="+39">+39 (Italia)</option>
                    <option value="+81">+81 (Japón)</option>
                    <option value="+86">+86 (China)</option>
                    <option value="+91">+91 (India)</option>
                    <option value="+52">+52 (México)</option>
                    <option value="+93">+93 (Afganistán)</option>
                    <option value="+355">+355 (Albania)</option>
                    <option value="+213">+213 (Argelia)</option>
                    <option value="+376">+376 (Andorra)</option>
                    <option value="+244">+244 (Angola)</option>
                    <option value="+54">+54 (Argentina)</option>
                    <option value="+374">+374 (Armenia)</option>
                    <option value="+297">+297 (Aruba)</option>
                    <option value="+61">+61 (Australia)</option>
                    <option value="+43">+43 (Austria)</option>
                    <option value="+994">+994 (Azerbaiyán)</option>
                    <option value="+973">+973 (Baréin)</option>
                    <option value="+880">+880 (Bangladesh)</option>
                    <option value="+375">+375 (Bielorrusia)</option>
                    <option value="+32">+32 (Bélgica)</option>
                    <option value="+501">+501 (Belice)</option>
                    <option value="+229">+229 (Benín)</option>
                    <option value="+975">+975 (Bután)</option>
                    <option value="+591">+591 (Bolivia)</option>
                    <option value="+387">+387 (Bosnia y Herzegovina)</option>
                    <option value="+267">+267 (Botsuana)</option>
                    <option value="+55">+55 (Brasil)</option>
                    <option value="+673">+673 (Brunéi)</option>
                    <option value="+359">+359 (Bulgaria)</option>
                    <option value="+226">+226 (Burkina Faso)</option>
                    <option value="+257">+257 (Burundi)</option>
                    <option value="+855">+855 (Camboya)</option>
                    <option value="+237">+237 (Camerún)</option>
                    <option value="+238">+238 (Cabo Verde)</option>
                    <option value="+236">+236 (República Centroafricana)</option>
                    <option value="+235">+235 (Chad)</option>
                    <option value="+56">+56 (Chile)</option>
                    <option value="+57">+57 (Colombia)</option>
                    <option value="+269">+269 (Comoras)</option>
                    <option value="+506">+506 (Costa Rica)</option>
                </select>
                <input type="tel" id="telefono" name="telefono" class="form-control" placeholder="Ingrese el número de teléfono" required>
            </div>
            <div class="invalid-feedback">
                Por favor, complete este campo.
            </div>
        </div>



        <div class="form-group">
            <label for="correoElectronico">Correo Electrónico:</label>
            <input type="email" id="correoElectronico" name="CorreoElectronico" class="form-control" required>
            <div class="invalid-feedback">
                Proporcione un correo electrónico válido.
            </div>
            <small class="form-text text-muted">
                El correo electrónico debe tener un formato válido (por ejemplo, usuario@dominio.com).
            </small>
        </div>


        <br />

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Guardar Reservación</button>
        </div>

        <br />


    </form>
</div>

<div class="modal" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmationModalLabel">Confirmación</h5>
            </div>
            <div class="modal-body">
                ¿Desea registrar la reservación?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="cancelarButton" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="guardarButton">Guardar</button>
            </div>
        </div>
    </div>
</div>


<script>
    (function () {
        'use strict';

        var forms = document.querySelectorAll('.needs-validation');

        Array.prototype.slice.call(forms).forEach(function (form) {
            form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                    event.preventDefault();
                    event.stopPropagation();
                } else {
                    // Mostrar el modal de confirmación
                    document.getElementById('confirmationModal').classList.add('show');
                    document.getElementById('confirmationModal').style.display = 'block';

                    // Prevenir el envío automático del formulario
                    event.preventDefault();
                }
                form.classList.add('was-validated');
            }, false);
        });

        // Agregar un listener para cerrar el modal manualmente
        document.getElementById('cancelarButton').addEventListener('click', function () {
            document.getElementById('confirmationModal').classList.remove('show');
            document.getElementById('confirmationModal').style.display = 'none';
        });

        document.getElementById('guardarButton').addEventListener('click', function () {
            document.querySelector('.needs-validation').submit();
            document.getElementById('confirmationModal').classList.remove('show');
            document.getElementById('confirmationModal').style.display = 'none';
        });
    })();

    function validarCedula(input) {
        var cedula = input.value.trim();
        var cedulaNacionalRegex = /^[1-9]-\d{4}-\d{4}$/;
        var dimexRegex = /^DIMEX-\d{4}-\d{4}$/;
        var errorMessageClass = 'error-message';

        // Elimina el mensaje de error anterior si existe
        var existingError = input.parentNode.querySelector(`.${errorMessageClass}`);
        if (existingError) {
            existingError.remove();
        }

        // Verificar si es un formato válido de cédula o DIMEX
        if (!(cedula.match(cedulaNacionalRegex) || cedula.match(dimexRegex))) {
            var errorMessage = document.createElement('div');
            errorMessage.textContent = "El formato de la cédula de identidad o DIMEX es incorrecto. Debe tener el formato 'X-XXXX-XXXX' o 'DIMEX-XXXX-XXXX'. Además, solo del 1-9 en el primer dígito se acepta.";
            errorMessage.classList.add(errorMessageClass);
            input.parentNode.appendChild(errorMessage);
            input.value = '';
        }
    }
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.0/gsap.min.js"></script>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        var mensaje = document.getElementById('mensaje');
        mensaje.style.display = 'flex';

        gsap.from(mensaje, { opacity: 0, y: -50, duration: 1, ease: "power4.out" });

        setTimeout(function () {
            gsap.to(mensaje, {
                opacity: 0, y: -50, duration: 1, ease: "power4.in", onComplete: function () {
                    mensaje.style.display = 'none';
                }
            });
        }, 3000);
    });
</script>

@if (TempData["Mensaje"] != null)
{
    <div id="mensaje" class="alert @TempData["Tipo"]" role="alert" style="display:none">
        <div class="d-flex align-items-center">
            <div class="message-container">
                @if (TempData["Tipo"].ToString() == "Ok")
                {
                    <div class="spinner-border mr-2 custom-spinner" role="status">  </div>
                }
                @if (TempData["Tipo"].ToString() == "error")
                {
                    <span class="mr-2" style="color: red;">&#10007;</span>
                }
            </div>
            @TempData["Mensaje"]
        </div>
    </div>
}



<script>
    // Utilizar la API de REST Countries para obtener la lista de países
    fetch('https://restcountries.com/v3.1/all')
        .then(response => response.json())
        .then(data => {
            // Obtener el elemento del select de nacionalidad
            var selectNacionalidad = document.getElementById('nacionalidad');

            // Iterar sobre la lista de países y agregar opciones al select
            data.forEach(country => {
                var option = document.createElement('option');
                option.value = country.name.common;
                option.textContent = country.name.common;
                selectNacionalidad.appendChild(option);
            });
        })
        .catch(error => console.error('Error al obtener la lista de países:', error));
</script>